### ISSUE TITLE
Element is not focused with #fill_in?

### ISSUE THREAD

**Issue by YusukeIwaki** [rubycdp/cuprite#157]
Hi, I'm trying several Capybara drivers.
When we evaluate with the following RSpec script (simple GitHub searching), Cuprite doesn't work as expected.

* Selenium: 10/10
* twalpole/apparition: 8/10 (https://github.com/twalpole/apparition/issues/76)
* rubycdp/cuprite: 0/10

```ruby
  it 'should search repository' do
    visit '/'

    fill_in('q', with: 'selenium')
    find('a[data-item-type="global_search"]').click

    output = all('.repo-list-item').map do |li|
      li.all('a').first.text
    end
    puts output
    expect(output).to include(match(/selenium/i))
  end
```

```
Failures:

  1) github search should search repository
     Failure/Error: find('a[data-item-type="global_search"]').click
     
     Capybara::ElementNotFound:
       Unable to find visible css "a[data-item-type=\"global_search\"]"
     # ./spec/feature/github_search_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/feature/github_search_spec.rb:8:in `block (2 levels) in <top (required)>'
```

![image](https://user-images.githubusercontent.com/11763113/120759217-c436a000-c54d-11eb-9b3a-9f22086ff357.png)

The search button appears only when textbox is focused.
It seems Cuprite inputs 'selenium' text without focusing into the textbox.

We can avoid this issue by explicitly put `find("input[name='q']").click` before fill_in, however I think it is not so good because some users already have selenium-based specs. It would be useful us to use the existing selenium-based specs also in Cuprite.

**Comment by dhnaranjo** [comment]
This issue is still causing trouble.

**Comment by jdelStrother** [comment]
I also ran into this, switching selenium -> cuprite. FWIW, I'm currently using this to work around it:

```ruby
  Capbyara::DSL.prepend(Module.new {
    def fill_in(selector, **opts)
      if page.driver.is_a?(Capybara::Cuprite::Driver)
        find(:fillable_field, selector).click
      end
      super
    end
  })
```
