### ISSUE TITLE
NoMethodError method monotonic_time for Ferrum

### ISSUE THREAD

**Issue by senid231** [rubycdp/cuprite#179]
After updating `cuprite` and `ferrum` from github master branch following error occurred:

```
NoMethodError:
       undefined method `monotonic_time' for Ferrum:Module
     # /var/cache/bundle/ruby/2.7.0/bundler/gems/cuprite-53a9195327b5/lib/capybara/cuprite/page.rb:71:in `find_modal'
     # /var/cache/bundle/ruby/2.7.0/bundler/gems/cuprite-53a9195327b5/lib/capybara/cuprite/driver.rb:354:in `accept_modal'
     # /var/cache/bundle/ruby/2.7.0/gems/capybara-3.35.3/lib/capybara/session.rb:850:in `accept_modal'
     # /var/cache/bundle/ruby/2.7.0/gems/capybara-3.35.3/lib/capybara/session.rb:657:in `accept_confirm'
     # /var/cache/bundle/ruby/2.7.0/gems/capybara-3.35.3/lib/capybara/dsl.rb:53:in `call'
     # /var/cache/bundle/ruby/2.7.0/gems/capybara-3.35.3/lib/capybara/dsl.rb:53:in `accept_confirm'
```

Gemfile.lock
```
GIT
  remote: https://github.com/rubycdp/cuprite.git
  revision: 53a9195327b52b32ceb050b4ca51431679c7510d

...

GIT
  remote: https://github.com/rubycdp/ferrum.git
  revision: afb9bb18b61f9ff9d637b8f4d48cdcc68b760540
```

**Comment by route** [comment]
https://github.com/rubycdp/cuprite/pull/173
