### ISSUE TITLE
PDF download timing out on Chromium > 127

### ISSUE THREAD

**Issue by brianclinkenbeard** [rubycdp/cuprite#279]
After updating past Chromium 127, running RSpec tests on PDF downloads now uniformly time out. We use this somewhat popular helper code to yield the download after clicking a PDF link:
```ruby
module DownloadHelpers
  TIMEOUT = 10
  PATH    = Capybara.save_path

  module_function

  def downloads
    Dir[PATH.join('*.{pdf,csv}')]
  end

  def download
    downloads.first
  end

  def download_content
    wait_for_download
    File.read(download)
  end

  def wait_for_download
    Timeout.timeout(TIMEOUT) do
      sleep 0.1 until downloaded?
    end
  end

  def downloaded?
    !downloading? && downloads.any?
  end

  def downloading?
    downloads.grep(/\.crdownload$/).any?
  end

  def clear_downloads
    FileUtils.rm_f(downloads)
  end
end

RSpec.configure do |config|
  config.include DownloadHelpers, type: :system

  config.before(:each, type: :system) do
    clear_downloads
  end
  config.after(:each, type: :system) do
    clear_downloads
  end
end
```
Waiting for a PDF download just hangs indefinitely. Watching with headless turned off, the PDF will never load in the new tab, however, trying this manually on a clean instance of Chromium will load the PDF perfectly. Perhaps an upstream regression with the CDP? Maybe also related: https://github.com/rubycdp/ferrum/discussions/457#discussioncomment-9151778

**Comment by huda-kh** [comment]
Any luck here? I am having the same issue with the same helper downloading a file (not a PDF).

**Comment by RST-J** [comment]
Thanks for the hint @brianclinkenbeard. Recently our tests related to file downloads started to fail and I had no clue why. We use the same or similar download handling code. I could get some tests running again by changing the way kt-paperclip constructs URLs (sic), but other still failed and I didn't really know how to proceed.

After reading your issue I thought, maybe that hit us as well.
We have a layered Docker setup for our app. The lowest layer is a base image derived from the ruby-3.3 image. Into this image we install additionally required external tools like chrome by adding the chrome repo from Google and installing the package `google-chrome-stable`. For an unrelated reason I built a new version of this image and after that the aforementioned issues started to occur.

I replaced the repo version of chrome by the headless variant found here: https://googlechromelabs.github.io/chrome-for-testing/ (back linked to from here https://developer.chrome.com/blog/chrome-for-testing, so I believe it is credible). First I used some older version (some 127) but then I wondered whether newer versions also work. And indeed, the currently latest stable version 131.0.6778.87 also works.

I changed our base image to install chrome from that archive file rather then the repo, so we have control over the actually used version and when to update.

**Comment by route** [comment]
It's not cuprite/ferrum issue, find the version that still works

**Comment by noniq** [comment]
For me, the problem only occurs with specific versions of cuprite / ferrum:

- cuprite 0.15 / ferrum 0.14: Dowloading works
- cuprite 0.15.1 / ferrum 0.15: Downloading fails 

It does not seem to be affected by the version of Chrome (I tried both Chrome for Testing v113.0.5672.0 and v133.0.6943.2).

Also, the problem seems to be triggered by opening a new (second) browser window during a test. We have tests like this (using RSpec and Capybara):

```ruby
scenario "foo" do
  visit root_path
  print_view_window = window_opened_by do
    click_on "Open print view"
  end
  within_window print_view_window do
    expect(page).to have_css("h1", text: "Dolor lorem ipsum")
  end
  print_view_window.close
end
```

These tests run fine. However, as soon as one such test has been executed, all *subsequent* tests trying to download a file fail. Again, this only happens with cuprite 0.15.1 / ferrum 0.15.

**Comment by route** [comment]
hm I think wrong target is active, I have a sense what's going on. Let me try to reproduce it with pure Cuprite test

**Comment by phyzical** [comment]
running `chromium-132.0.6834.83-1.el9` on rocky linux both seem to timeout for me, so it may still be chromium related

```
 cuprite (0.15)
      capybara (~> 3.0)
      ferrum (~> 0.14.0)
```

and

```
cuprite (0.15.1)
      capybara (~> 3.0)
      ferrum (~> 0.15.0)
```

**Comment by brianclinkenbeard** [comment]
> hm I think wrong target is active, I have a sense what's going on. Let me try to reproduce it with pure Cuprite test

Did this go anywhere? Any way I could help?

**Comment by neanias** [comment]
I'm also seeing problems with Chrome when using Cuprite >=0.15.1. We see recurring issues with `Failed to find browser context for id <hex id>`.

<summary>Ferrum traceback</summary>
<details>
```
1.1) Failure/Error: visit patients_path

          Ferrum::BrowserError:
            Failed to find browser context for id 1274A81C8D5668C26F3AA90EFB5D8A34
          # /usr/local/bundle/gems/ferrum-0.17.1/lib/ferrum/client.rb:175:in 'Ferrum::Client#raise_browser_error'
          # /usr/local/bundle/gems/ferrum-0.17.1/lib/ferrum/client.rb:99:in 'Ferrum::Client#send_message'
          # /usr/local/bundle/gems/ferrum-0.17.1/lib/ferrum/client.rb:24:in 'Ferrum::SessionClient#command'
          # /usr/local/bundle/gems/ferrum-0.17.1/lib/ferrum/page.rb:358:in 'Ferrum::Page#command'
          # /usr/local/bundle/gems/ferrum-0.17.1/lib/ferrum/downloads.rb:28:in 'Ferrum::Downloads#set_behavior'
          # /usr/local/bundle/gems/ferrum-0.17.1/lib/ferrum/page.rb:477:in 'Ferrum::Page#prepare_page'
          # /usr/local/bundle/gems/cuprite-0.17/lib/capybara/cuprite/page.rb:144:in 'Capybara::Cuprite::Page#prepare_page'
          # /usr/local/bundle/gems/ferrum-0.17.1/lib/ferrum/page.rb:94:in 'Ferrum::Page#initialize'
          # /usr/local/bundle/gems/cuprite-0.17/lib/capybara/cuprite/page.rb:27:in 'Capybara::Cuprite::Page#initialize'
          # /usr/local/bundle/gems/cuprite-0.17/lib/capybara/cuprite/browser.rb:261:in 'Class#new'
          # /usr/local/bundle/gems/cuprite-0.17/lib/capybara/cuprite/browser.rb:261:in 'Capybara::Cuprite::Browser#attach_page'
          # /usr/local/bundle/gems/cuprite-0.17/lib/capybara/cuprite/browser.rb:33:in 'Capybara::Cuprite::Browser#page'
          # /usr/local/bundle/gems/cuprite-0.17/lib/capybara/cuprite/browser.rb:75:in 'Capybara::Cuprite::Browser#visit'
          # /usr/local/bundle/gems/cuprite-0.17/lib/capybara/cuprite/driver.rb:57:in 'Capybara::Cuprite::Driver#visit'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/session.rb:281:in 'Capybara::Session#visit'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/dsl.rb:52:in 'Method#call'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/dsl.rb:52:in 'Capybara::DSL#visit'
          # ./spec/system/sidebar_spec.rb:71:in 'block (3 levels) in <top (required)>'
          # /usr/local/bundle/gems/webmock-3.25.1/lib/webmock/rspec.rb:39:in 'block (2 levels) in <top (required)>'
```

**Comment by brianclinkenbeard** [comment]
Anyone found a workaround for this?

**Comment by brianclinkenbeard** [comment]
This seemed to be related to the PDF viewer feature being included by default headless chromium after v127. Adding this to `config/environments/test.rb`:
```ruby
  config.active_storage.content_types_allowed_inline -= ['application/pdf']
```
Serves the PDF as a download and works around this issue for me.

**Comment by route** [comment]
linking https://github.com/rubycdp/ferrum/discussions/337
but what's your content disposition? why chrome shows it instead of downloading?

**Comment by brianclinkenbeard** [comment]
@route Prior to this config change, the Rails ActiveStorage default was to serve PDFs with `content-disposition: inline`. I believe prior to v128, chromium did not include the built-in PDF viewer in headless mode, so they would be downloaded as attachments anyway.

**Comment by route** [comment]
> [@route](https://github.com/route) Prior to this config change, the Rails ActiveStorage default was to serve PDFs with `content-disposition: inline`. I believe prior to v128, chromium did not include the built-in PDF viewer in headless mode, so they would be downloaded as attachments anyway.

Got it, that makes total sense, as 128 was the first headless=new mode switch.
